# Generated by Django 4.1.3 on 2022-11-25 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_pelicula_portada'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'permissions': [('admin_generic', 'Puede Editar y Crear Peliculas')]},
        ),
        migrations.AddField(
            model_name='pelicula',
            name='Precio',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Cine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=30)),
                ('Ubicacion', models.TextField(max_length=50)),
                ('Proyector', models.CharField(choices=[('Epson', 'Epson'), ('Canon', 'Canon'), ('Generic', 'Generic')], default='Epson', max_length=10)),
                ('pelicula', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.pelicula')),
            ],
        ),
    ]
