# Generated by Django 4.1.3 on 2022-12-02 00:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_pelicula_options_pelicula_precio_cine'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pelicula',
            options={'permissions': [('admin_generic', 'Puede Editar y Crear Peliculas'), ('suscriptor', 'Solo mostrara el detalle')]},
        ),
    ]
